project:
  type: website

website:
  title: "John Glendenning"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: SPARQL.qmd
        text: "SPARQL"
      - text: "EPPS6356"
        menu:
        - href: prepare01.qmd
          text: "Prepare for Class 01"
        - href: prepare02.qmd
          text: "Prepare for Class 02"
        - href: assignment01.qmd
          text: "Assignment 01"
      - text: "Project"
        menu:
        - href: project01.qmd
          text: "Brainstorming"
      - text: "Coins"
        menu:
        - href: coins01.qmd
          text: "Brainstorming"
      - href: about.qmd
        text: "About"

format:
  html:
    include-in-header:
      - text: |
          <meta name="robots" content="noindex, nofollow">
    theme:
      - cerulean
      - brand
    css: styles.css
    toc: true


editor: source



