project:
  type: website

website:
  title: "John Glendenning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - SPARQL.qmd
      - EPPS6323

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

